// <auto-generated />
using System;
using Capstone.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Capstone.Migrations
{
    [DbContext(typeof(IdentityContext))]
    partial class IdentityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Capstone.Models.AnimeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EpisodeCount");

                    b.Property<string>("ImagePath");

                    b.Property<int>("Members");

                    b.Property<int>("Popularity");

                    b.Property<string>("Premiered")
                        .IsRequired();

                    b.Property<double>("Rating");

                    b.Property<string>("RecommendedAge")
                        .IsRequired();

                    b.Property<string>("Source")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("Synopsis")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("AnimeItem");
                });

            modelBuilder.Entity("Capstone.Models.AnimeList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnimeItemId");

                    b.Property<int>("CompleteStatus");

                    b.Property<Guid>("UserId");

                    b.Property<int>("UserProgress");

                    b.Property<int>("UserRating");

                    b.HasKey("Id");

                    b.HasIndex("AnimeItemId");

                    b.HasIndex("UserId");

                    b.ToTable("AnimeList");
                });

            modelBuilder.Entity("Capstone.Models.AnimeReviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnimeItemId");

                    b.Property<DateTime>("PostDate");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnimeItemId");

                    b.HasIndex("UserId");

                    b.ToTable("AnimeReviews");
                });

            modelBuilder.Entity("Capstone.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnimeItemId");

                    b.Property<int?>("MangaItemId");

                    b.Property<int?>("NovelItemId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnimeItemId");

                    b.HasIndex("MangaItemId");

                    b.HasIndex("NovelItemId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Capstone.Models.FriendList", b =>
                {
                    b.Property<Guid?>("UserId");

                    b.Property<Guid?>("FriendId");

                    b.Property<DateTime>("RequestSent");

                    b.Property<int>("RequestStatus");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("Capstone.Models.MangaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EpisodeCount");

                    b.Property<string>("ImagePath");

                    b.Property<int>("Members");

                    b.Property<int>("Popularity");

                    b.Property<string>("Premiered")
                        .IsRequired();

                    b.Property<double>("Rating");

                    b.Property<string>("RecommendedAge")
                        .IsRequired();

                    b.Property<string>("Source")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("Synopsis")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("MangaItem");
                });

            modelBuilder.Entity("Capstone.Models.MangaList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompleteStatus");

                    b.Property<int>("MangaItemId");

                    b.Property<Guid>("UserId");

                    b.Property<int>("UserProgress");

                    b.Property<int>("UserRating");

                    b.HasKey("Id");

                    b.HasIndex("MangaItemId");

                    b.HasIndex("UserId");

                    b.ToTable("MangaList");
                });

            modelBuilder.Entity("Capstone.Models.MangaReviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MangaItemId");

                    b.Property<DateTime>("PostDate");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MangaItemId");

                    b.HasIndex("UserId");

                    b.ToTable("MangaReviews");
                });

            modelBuilder.Entity("Capstone.Models.NovelItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EpisodeCount");

                    b.Property<string>("ImagePath");

                    b.Property<int>("Members");

                    b.Property<int>("Popularity");

                    b.Property<string>("Premiered")
                        .IsRequired();

                    b.Property<double>("Rating");

                    b.Property<string>("RecommendedAge")
                        .IsRequired();

                    b.Property<string>("Source")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("Synopsis")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("NovelItem");
                });

            modelBuilder.Entity("Capstone.Models.NovelList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompleteStatus");

                    b.Property<int>("NovelItemId");

                    b.Property<Guid>("UserId");

                    b.Property<int>("UserProgress");

                    b.Property<int>("UserRating");

                    b.HasKey("Id");

                    b.HasIndex("NovelItemId");

                    b.HasIndex("UserId");

                    b.ToTable("NovelList");
                });

            modelBuilder.Entity("Capstone.Models.NovelReviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NovelItemId");

                    b.Property<DateTime>("PostDate");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("NovelItemId");

                    b.HasIndex("UserId");

                    b.ToTable("NovelReviews");
                });

            modelBuilder.Entity("Capstone.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Capstone.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<DateTime>("JoinedDate");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("ProfileImagePath");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Capstone.Models.AnimeList", b =>
                {
                    b.HasOne("Capstone.Models.AnimeItem", "Anime")
                        .WithMany("AnimeLists")
                        .HasForeignKey("AnimeItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Capstone.Models.User", "User")
                        .WithMany("AnimeList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Capstone.Models.AnimeReviews", b =>
                {
                    b.HasOne("Capstone.Models.AnimeItem", "Anime")
                        .WithMany("Reviews")
                        .HasForeignKey("AnimeItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Capstone.Models.User", "User")
                        .WithMany("AnimeReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Capstone.Models.Favorite", b =>
                {
                    b.HasOne("Capstone.Models.AnimeItem", "AnimeFavorite")
                        .WithMany()
                        .HasForeignKey("AnimeItemId");

                    b.HasOne("Capstone.Models.MangaItem", "MangaFavorite")
                        .WithMany()
                        .HasForeignKey("MangaItemId");

                    b.HasOne("Capstone.Models.NovelItem", "NovelFavorite")
                        .WithMany()
                        .HasForeignKey("NovelItemId");
                });

            modelBuilder.Entity("Capstone.Models.FriendList", b =>
                {
                    b.HasOne("Capstone.Models.User", "Friend")
                        .WithMany("FriendUsers")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Capstone.Models.User", "User")
                        .WithMany("UserFriends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Capstone.Models.MangaList", b =>
                {
                    b.HasOne("Capstone.Models.MangaItem", "Manga")
                        .WithMany("MangaLists")
                        .HasForeignKey("MangaItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Capstone.Models.User", "User")
                        .WithMany("MangaList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Capstone.Models.MangaReviews", b =>
                {
                    b.HasOne("Capstone.Models.MangaItem", "Manga")
                        .WithMany("Reviews")
                        .HasForeignKey("MangaItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Capstone.Models.User", "User")
                        .WithMany("MangaReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Capstone.Models.NovelList", b =>
                {
                    b.HasOne("Capstone.Models.NovelItem", "Novel")
                        .WithMany("NovelLists")
                        .HasForeignKey("NovelItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Capstone.Models.User", "User")
                        .WithMany("NovelList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Capstone.Models.NovelReviews", b =>
                {
                    b.HasOne("Capstone.Models.NovelItem", "Novel")
                        .WithMany("Reviews")
                        .HasForeignKey("NovelItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Capstone.Models.User", "User")
                        .WithMany("NovelReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Capstone.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Capstone.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Capstone.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Capstone.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Capstone.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Capstone.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
